config/routes.rb
TripSorter::Application.routes.draw do
  resources :boarding_cards

end

app/models/boarding_card.rb
class BoardingCard < ActiveRecord::Base
	validates_presence_of :origin
	validates_presence_of :destination
	validates_presence_of :form_of_transport

	def trip_origin (boarding_cards)
		origin = ''
		position = 0
		while origin == ''
			possible_origin = boarding_cards[position][:origin]
			cont = 0
			@boarding_cards.each do |card|
				if possible_origin == @card[:destination]
					cont += 1
				end
			end

			if cont == 0
				origin = possible_origin
			end

			position += 1
		end

		return origin
	end

	def sort_cards (boarding_cards)
		sorted = []
		position = 0

		origin = trip_origin (boarding_cards)

		boarding_cards.each do |card|
			if card[:origin] == origin
				destination = card[:destination]
				sorted << card
			end
		end

		while sorted.length <= @boarding_cards.length
			@boarding_cards.each do |card|
				if destination == card[:origin]
					sorted << card
					origin = card[:origin]
					destination = card[:destination]
				end
			end
		end

		return sorted
	end

	def indications (boarding_card)
    	indications = "Take "+ boarding_card[:form_of_transport] + " from " + boarding_card[:origin] + " to " + boarding_card[:destination] + "." + boarding_card[:seat] + boarding_card[:extra_info]
  	end

  	def trip (boarding_cards)
  		sorted_cards = sort_cards(boarding_cards)

  		sorted_cards.each do |card|
  			puts indications(card)
  		end
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boarding_cards_controller.rb
class BoardingCardsController < ApplicationController
  before_action :set_boarding_card, only: [:show, :edit, :update, :destroy]

  # GET /boarding_cards
  # GET /boarding_cards.json
  def index
    @boarding_cards = BoardingCard.all
  end

  # GET /boarding_cards/1
  # GET /boarding_cards/1.json
  def show
  end

  # GET /boarding_cards/new
  def new
    @boarding_card = BoardingCard.new
  end

  # GET /boarding_cards/1/edit
  def edit
  end

  # POST /boarding_cards
  # POST /boarding_cards.json
  def create
    @boarding_card = BoardingCard.new(boarding_card_params)

    respond_to do |format|
      if @boarding_card.save
        format.html { redirect_to @boarding_card, notice: 'Boarding card was successfully created.' }
        format.json { render action: 'show', status: :created, location: @boarding_card }
      else
        format.html { render action: 'new' }
        format.json { render json: @boarding_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boarding_cards/1
  # PATCH/PUT /boarding_cards/1.json
  def update
    respond_to do |format|
      if @boarding_card.update(boarding_card_params)
        format.html { redirect_to @boarding_card, notice: 'Boarding card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @boarding_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boarding_cards/1
  # DELETE /boarding_cards/1.json
  def destroy
    @boarding_card.destroy
    respond_to do |format|
      format.html { redirect_to boarding_cards_url }
      format.json { head :no_content }
    end
  end

  def trip
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boarding_card
      @boarding_card = BoardingCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boarding_card_params
      params.require(:boarding_card).permit(:origin, :destination, :form_of_transport, :seat, :extra_info)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boarding_cards_helper.rb
module BoardingCardsHelper
end

app/views/boarding_cards/_form.html.erb
<%= form_for(@boarding_card) do |f| %>
  <% if @boarding_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boarding_card.errors.count, "error") %> prohibited this boarding_card from being saved:</h2>

      <ul>
      <% @boarding_card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :form_of_transport %><br>
    <%= f.text_field :form_of_transport %>
  </div>
  <div class="field">
    <%= f.label :seat %><br>
    <%= f.text_field :seat %>
  </div>
  <div class="field">
    <%= f.label :extra_info %><br>
    <%= f.text_field :extra_info %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boarding_cards/edit.html.erb
<h1>Editing Boarding Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @boarding_card %> |
<%= link_to 'Back', boarding_cards_path %>

app/views/boarding_cards/index.html.erb
<h1>Listing Boarding Cards</h1>

<table>
  <thead>
    <tr>
      <th>Origin</th>
      <th>Destination</th>
      <th>Form of Transport</th>
      <th>Seat</th>
      <th>Extra Info</th>
    </tr>
  </thead>

  <tbody>
    <% @boarding_cards.each do |boarding_card| %>
      <tr>
        <td><%= boarding_card.origin %></td>
        <td><%= boarding_card.destination %></td>
        <td><%= boarding_card.form_of_transport %></td>
        <td><%= boarding_card.seat %></td>
        <td><%= boarding_card.extra_info %></td>
        <td><%= link_to 'Show', boarding_card %></td>
        <td><%= link_to 'Edit', edit_boarding_card_path(boarding_card) %></td>
        <td><%= link_to 'Destroy', boarding_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Boarding card', new_boarding_card_path %>

app/views/boarding_cards/new.html.erb
<h1>New Boarding Card</h1>

<%= render 'form' %>

<%= link_to 'Back', boarding_cards_path %>

app/views/boarding_cards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_boarding_card_path(@boarding_card) %> |
<%= link_to 'Back', boarding_cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TripSorter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>